'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls.Common

    Partial Public Class DocumentationUC

        '''<summary>
        '''hdIsIncomplete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdIsIncomplete As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdIsValidateFailed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdIsValidateFailed As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdCurrentObjectUniqueId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdCurrentObjectUniqueId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''lbldocumentationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbldocumentationUC As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''FormFillingInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FormFillingInstructions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblFormFillingInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFormFillingInstructions As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Image1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''hlAddNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlAddNew As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''rptdocumentation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptdocumentation As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''lblPopupMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPopupMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''vldsPopupRequiredGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vldsPopupRequiredGroup As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''ExperienceType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ExperienceType As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblExperienceType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExperienceType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlExperienceType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlExperienceType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rqExperienceType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqExperienceType As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''ExperienceDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ExperienceDetail As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblExperienceDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExperienceDetail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtExperienceDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExperienceDetail As Global.System.Web.UI.HtmlControls.HtmlTextArea

        '''<summary>
        '''rqExperienceDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqExperienceDetail As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''UploadFileAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UploadFileAttachment As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblUploadFileAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUploadFileAttachment As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''fuUploadFileAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fuUploadFileAttachment As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''rqUploadFileAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqUploadFileAttachment As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''rqPdfFileExtension control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqPdfFileExtension As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''hlUploadFileAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlUploadFileAttachment As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''imgDeleteAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgDeleteAttachment As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''hfDeleteFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfDeleteFile As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''btnSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
