'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls.Common

    Partial Public Class ExamChoiceUC

        '''<summary>
        '''hdIsIncomplete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdIsIncomplete As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdIsValidateFailed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdIsValidateFailed As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdSurveyId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdSurveyId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdExamChoiceQuestionId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdExamChoiceQuestionId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdExamChoiceResponseId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdExamChoiceResponseId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdExamChoiceResponseAnswerId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdExamChoiceResponseAnswerId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''lblExamChoiceUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExamChoiceUC As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''FormFillingInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FormFillingInstructions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblFormFillingInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFormFillingInstructions As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rptExamChoice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptExamChoice As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
