'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls.Common

    Partial Public Class OrganizationInvolvement

        '''<summary>
        '''hdIsIncomplete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdIsIncomplete As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdIsValidateFailed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdIsValidateFailed As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdCurrentObjectUniqueId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdCurrentObjectUniqueId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''lblOrganizationInvolvement control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOrganizationInvolvement As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''FormFillingInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FormFillingInstructions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblFormFillingInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFormFillingInstructions As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOptionTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOptionTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''imgAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgAdd As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''hlAddNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlAddNew As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''rptInvolvement control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptInvolvement As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''lblTotalCE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalCE As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''panelPopup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelPopup As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblPopupMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPopupMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''vldsPopupRequiredGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vldsPopupRequiredGroup As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''Title control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Title As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''FullName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FullName As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblFullName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFullName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtFullName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFullName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqFullName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqFullName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Point control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Point As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblPoint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPoint As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtNumberOfHours control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNumberOfHours As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqPoint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqPoint As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''RegularExpressionValidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''Role control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Role As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRole As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRole As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqRole As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Date control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents [Date] As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDate As Global.AMC.DNN.Modules.CertRecert.Controls.Reusable.AMCDatetime

        '''<summary>
        '''rqDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''cusValidOtherBoard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cusValidOtherBoard As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''TypeOfCE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TypeOfCE As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblTypeOfCE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTypeOfCE As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlCEType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCEType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rqTypeOfCE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqTypeOfCE As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''btnSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
