'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls.Common

    Partial Public Class ReferenceAndVerificationUC

        '''<summary>
        '''hdDeletedFileList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdDeletedFileList As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdIsIncomplete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdIsIncomplete As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdIsValidateFailed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdIsValidateFailed As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdCurrentObjectUniqueId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdCurrentObjectUniqueId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''lblReferenceAndVerificationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReferenceAndVerificationUC As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''FormFillingInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FormFillingInstructions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblFormFillingInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFormFillingInstructions As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Image1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''hlAddNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlAddNew As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''rptPrintReferences control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptPrintReferences As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''rptReferences control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptReferences As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''hdAlternativeVerificationSurveyId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdAlternativeVerificationSurveyId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''rptAlternativeVerification control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptAlternativeVerification As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''panelPopup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelPopup As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblPopupMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPopupMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''vldsPopupRequiredGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vldsPopupRequiredGroup As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''FirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FirstName As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFirstName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqFirstName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''MiddleName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MiddleName As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblMiddleName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMiddleName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtMiddleName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMiddleName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqMiddleName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqMiddleName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Name control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Name As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Title control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Title As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Degree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Degree As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblDegree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDegree As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtDegree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDegree As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqDegree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqDegree As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Employer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Employer As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblEmployer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmployer As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtEmployer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmployer As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqEmployer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqEmployer As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''PrefContactMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PrefContactMethod As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblPrefContactMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPrefContactMethod As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlPrefContactMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPrefContactMethod As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rqPrefContactMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqPrefContactMethod As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''ContactClass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ContactClass As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblContactClass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblContactClass As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rdlContactClass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdlContactClass As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''WorkAddress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkAddress1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblWorkAddress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkAddress1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtWorkAddress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWorkAddress1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqWorkAddress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqWorkAddress1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''WorkAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkAddress2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblWorkAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkAddress2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtWorkAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWorkAddress2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqWorkAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqWorkAddress2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''WorkAddress3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkAddress3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblWorkAddress3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkAddress3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtWorkAddress3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWorkAddress3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqWorkAddress3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqWorkAddress3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''WorkAddress4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkAddress4 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblWorkAddress4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkAddress4 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtWorkAddress4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWorkAddress4 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqWorkAddress4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqWorkAddress4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''City control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents City As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCity As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqCity As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''State control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents State As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblState As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlWorkState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlWorkState As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rqState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqState As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''WorkZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkZip As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblWorkZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkZip As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtWorkZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWorkZip As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqWorkZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqWorkZip As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''WorkTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkTelephone As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblWorkTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkTelephone As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtWorkTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWorkTelephone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqWorkTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqWorkTelephone As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''maskedWorkPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents maskedWorkPhone As Global.AjaxControlToolkit.MaskedEditExtender

        '''<summary>
        '''maskedWorkPhoneValidator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents maskedWorkPhoneValidator As Global.AjaxControlToolkit.MaskedEditValidator

        '''<summary>
        '''WorkEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkEmail As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblWorkEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkEmail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtWorkEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWorkEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqWorkEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqWorkEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''regexWorkEmailValid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents regexWorkEmailValid As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''HomeAddress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeAddress1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeAddress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeAddress1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtHomeAddress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHomeAddress1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqHomeAddress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqHomeAddress1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''HomeAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeAddress2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeAddress2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtHomeAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHomeAddress2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqHomeAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqHomeAddress2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''HomeAddress3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeAddress3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeAddress3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeAddress3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtHomeAddress3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHomeAddress3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqHomeAddress3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqHomeAddress3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''HomeAddress4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeAddress4 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeAddress4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeAddress4 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtHomeAddress4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHomeAddress4 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqHomeAddress4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqHomeAddress4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''HomeCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeCity As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeCity As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtHomeCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHomeCity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqHomeCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqHomeCity As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''HomeState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeState As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeState As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlHomeState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlHomeState As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rqHomeState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqHomeState As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''HomeZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeZip As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeZip As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtHomeZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHomeZip As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqHomeZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqHomeZip As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''HomeTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeTelephone As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeTelephone As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtHomeTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHomeTelephone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqHomeTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqHomeTelephone As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''maskedHomePhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents maskedHomePhone As Global.AjaxControlToolkit.MaskedEditExtender

        '''<summary>
        '''maskedHomePhoneValidator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents maskedHomePhoneValidator As Global.AjaxControlToolkit.MaskedEditValidator

        '''<summary>
        '''HomeEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeEmail As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeEmail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtHomeEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHomeEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqHomeEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqHomeEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''regexHomeEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents regexHomeEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''UploadFileAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UploadFileAttachment As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblUploadFileAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUploadFileAttachment As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''fuUploadFileAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fuUploadFileAttachment As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''rqUploadFileAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqUploadFileAttachment As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''rqPdfFileExtension control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqPdfFileExtension As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''hlUploadFileAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlUploadFileAttachment As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''imgDeleteAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgDeleteAttachment As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''hfDeleteFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfDeleteFile As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''btnSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
