'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls.Common

    Partial Public Class Research

        '''<summary>
        '''hdIsIncomplete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdIsIncomplete As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdIsValidateFailed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdIsValidateFailed As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdCurrentObjectUniqueId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdCurrentObjectUniqueId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''lblResearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblResearch As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''FormFillingInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FormFillingInstructions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblFormFillingInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFormFillingInstructions As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOptionTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOptionTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Image1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''hlAddNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlAddNew As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''rptResearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptResearch As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''lblTotalCE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalCE As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''panelPopup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelPopup As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblPopupMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPopupMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''vldsPopupRequiredGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vldsPopupRequiredGroup As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''ResearchTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ResearchTitle As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblResearchTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblResearchTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtResearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtResearch As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqResearchTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqResearchTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''CompletionDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CompletionDate As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblCompletionDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCompletionDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtCompletionDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCompletionDate As Global.AMC.DNN.Modules.CertRecert.Controls.Reusable.AMCDatetime

        '''<summary>
        '''rqCompletionDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqCompletionDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''cusValidOtherBoard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cusValidOtherBoard As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''Organization control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Organization As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblOrganization control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOrganization As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtOrganization control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOrganization As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqOrganization control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqOrganization As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Point control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Point As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblPoint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPoint As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtApprovedCE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtApprovedCE As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqPoint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqPoint As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''RegularExpressionValidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''CEType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CEType As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblCEType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCEType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlCEType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCEType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rqCEType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqCEType As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''btnSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
