'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls.Reusable

    Partial Public Class AMCDatetime

        '''<summary>
        '''divAmcDateTimeContainer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divAmcDateTimeContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtDatetime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDatetime As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imgDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgDate As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''calendarExtender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calendarExtender As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''vldDateTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vldDateTime As Global.System.Web.UI.WebControls.CompareValidator
    End Class
End Namespace
