'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls.FormConfigurations

    Partial Public Class CETypeSettingsUC

        '''<summary>
        '''hdCurrentSelectedProgramTypeCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdCurrentSelectedProgramTypeCode As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdCurrentSelectedCETypeCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdCurrentSelectedCETypeCode As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdCurrentSectionPopupOpenningId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdCurrentSectionPopupOpenningId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdCurrentSectionPopupOpenningTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdCurrentSectionPopupOpenningTitle As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdCurrentObjectUniqueId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdCurrentObjectUniqueId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''Label6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProgramTypeSettingsGuideline control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProgramTypeSettingsGuideline As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rptProgramTypesOption2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptProgramTypesOption2 As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''lblCEWeightSettingsHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCEWeightSettingsHeader As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCETypeSettingsGuideline control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCETypeSettingsGuideline As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCEWeightMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCEWeightMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Image1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''hlAddNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlAddNew As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''rptCEWeightSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptCEWeightSettings As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''lblCEWeightPopupMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCEWeightPopupMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProgramTypeHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProgramTypeHeader As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlProgramType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlProgramType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblCETypeHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCETypeHeader As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlCEType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCEType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''RequiredFieldValidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Label4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtMinCE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMinCE As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidator6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidator6 As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''Label5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtMaxCE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaxCE As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidator5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidator5 As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''compareValidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents compareValidator1 As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''lblWeightHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWeightHeader As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtCEWeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCEWeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RequiredFieldValidator17 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator17 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''RegularExpressionValidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''btnSaveCEWeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSaveCEWeight As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancelSaveCEWeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancelSaveCEWeight As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
