'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls.FormConfigurations

    Partial Public Class ValidationRuleSettingsUC

        '''<summary>
        '''lblValidationRuleInstruction control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblValidationRuleInstruction As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rptValidationRules control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptValidationRules As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
