'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls.Certifications

    Partial Public Class CertUC

        '''<summary>
        '''hdCurrentSectionPopupOpenningId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdCurrentSectionPopupOpenningId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdCurrentSectionPopupOpenningTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdCurrentSectionPopupOpenningTitle As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdSaveSuccessful control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdSaveSuccessful As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdStepCompletedList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdStepCompletedList As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''lblCertUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCertUC As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rtsStepMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rtsStepMenu As Global.Telerik.Web.UI.RadTabStrip

        '''<summary>
        '''lblMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''vldsGeneral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vldsGeneral As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''mvCertification control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mvCertification As Global.System.Web.UI.WebControls.MultiView

        '''<summary>
        '''RegistrationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegistrationUC As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sectionRegistrationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionRegistrationUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.RegistrationUC

        '''<summary>
        '''SupervisorUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SupervisorUC As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sectionSupervisorUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionSupervisorUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.SupervisorUC

        '''<summary>
        '''ExamChoiceUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ExamChoiceUC As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sectionExamChoiceUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionExamChoiceUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.ExamChoiceUC

        '''<summary>
        '''RecertEligibilityUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RecertEligibilityUC As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sectionRecertEligibilityUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionRecertEligibilityUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.RecertEligibilityUC

        '''<summary>
        '''EducationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EducationUC As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sectionEducationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionEducationUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.EducationUC

        '''<summary>
        '''CategoryCertifiedCME control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CategoryCertifiedCME As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sectionCategoryCertifiedCME control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionCategoryCertifiedCME As Global.AMC.DNN.Modules.CertRecert.Controls.Common.CategoryCertifiedCME

        '''<summary>
        '''Licensure control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Licensure As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sectionLicensure control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionLicensure As Global.AMC.DNN.Modules.CertRecert.Controls.Common.Licensure

        '''<summary>
        '''ControlSubstanceAuthorizationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ControlSubstanceAuthorizationUC As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sectionControlSubstanceAuthorizationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionControlSubstanceAuthorizationUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.ControlSubstanceAuthorizationUC

        '''<summary>
        '''BoardCertificationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BoardCertificationUC As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sectionBoardCertificationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionBoardCertificationUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.BoardCertificationUC

        '''<summary>
        '''PracticeExperienceDetailsUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PracticeExperienceDetailsUC As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sectionPracticeExperienceDetailsUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionPracticeExperienceDetailsUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.PracticeExperienceDetailsUC

        '''<summary>
        '''ReferenceAndVerificationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReferenceAndVerificationUC As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sectionReferenceAndVerificationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionReferenceAndVerificationUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.ReferenceAndVerificationUC

        '''<summary>
        '''StandardQuestionaireUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StandardQuestionaireUC As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sectionStandardQuestionaireUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionStandardQuestionaireUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.StandardQuestionaireUC

        '''<summary>
        '''ProfessionalPracticeQuestionnaire control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProfessionalPracticeQuestionnaire As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sectionProfessionalPracticeQuestionnaire control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionProfessionalPracticeQuestionnaire As Global.AMC.DNN.Modules.CertRecert.Controls.Common.ProfessionalPracticeQuestionnaire

        '''<summary>
        '''ProfessionalPracticeSetting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProfessionalPracticeSetting As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sectionProfessionalPracticeSetting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionProfessionalPracticeSetting As Global.AMC.DNN.Modules.CertRecert.Controls.Common.ProfessionalPracticeSetting

        '''<summary>
        '''ScopeUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ScopeUC As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sectionScopeUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionScopeUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.ScopeUC

        '''<summary>
        '''DocumentationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DocumentationUC As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sectionDocumentationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionDocumentationUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.DocumentationUC

        '''<summary>
        '''ProfessionalPracticeExperienceUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProfessionalPracticeExperienceUC As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sectionProfessionalPracticeExperienceUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionProfessionalPracticeExperienceUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.ProfessionalPracticeExperienceUC

        '''<summary>
        '''btnBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btbSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btbSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnNext control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNext As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPrint As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
