'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls.Common

    Partial Public Class ContinuingEducation

        '''<summary>
        '''hdIsIncomplete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdIsIncomplete As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdIsValidateFailed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdIsValidateFailed As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdCurrentObjectUniqueId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdCurrentObjectUniqueId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''lblErrorMessageChangeOption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorMessageChangeOption As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblContinuingEducation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblContinuingEducation As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''FormFillingInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FormFillingInstructions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblFormFillingInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFormFillingInstructions As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOptionTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOptionTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''imgAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgAdd As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''hlAddNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlAddNew As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''rptcontinuingEducation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptcontinuingEducation As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''lblTotalCE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalCE As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''panelPopup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelPopup As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblPopupMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPopupMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''vldsPopupRequiredGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vldsPopupRequiredGroup As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''ProgramTittle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProgramTittle As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblProgramTittle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProgramTittle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtProgramTittle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProgramTittle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqProgramTittle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqProgramTittle As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''NameOfOrganizationProviding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NameOfOrganizationProviding As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblNameOfOrganizationProviding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNameOfOrganizationProviding As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtNameOfOrganizationProviding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNameOfOrganizationProviding As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqNameOfOrganizationProviding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqNameOfOrganizationProviding As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''NameOfOrganizationApproved control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NameOfOrganizationApproved As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblNameOfOrganizationApproved control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNameOfOrganizationApproved As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtNameOfOrganizationApproved control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNameOfOrganizationApproved As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqNameOfOrganizationApproved control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqNameOfOrganizationApproved As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''ApprovodContacHours control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ApprovodContacHours As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblApprovodContacHours control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblApprovodContacHours As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtApprovodContacHours control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtApprovodContacHours As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RegularExpressionValidator2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidator2 As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''rqApprovodContacHours control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqApprovodContacHours As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Date control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents [Date] As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDate As Global.AMC.DNN.Modules.CertRecert.Controls.Reusable.AMCDatetime

        '''<summary>
        '''rqDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''cusValidOtherBoard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cusValidOtherBoard As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''Point control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Point As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblPoint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPoint As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPoint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPoint As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqPoint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqPoint As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''RegularExpressionValidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''CEType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CEType As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblCEType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCEType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlCEType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCEType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rqCEType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqCEType As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''btnSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
