'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls.Common

    Partial Public Class RegistrationUC

        '''<summary>
        '''hdIsIncomplete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdIsIncomplete As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdIsValidateFailed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdIsValidateFailed As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdSurveyId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdSurveyId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''lblRegistrationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRegistrationUC As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''FormFillingInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FormFillingInstructions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblFormFillingInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFormFillingInstructions As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tblRegistration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblRegistration As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''FirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FirstName As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFirstName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFirstNameValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFirstNameValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''MiddleName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MiddleName As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblMiddleName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMiddleName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMiddleNameValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMiddleNameValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LastName As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLastName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLastNameValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLastNameValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''HomeAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeAddress As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeAddress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblHomeAddressValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeAddressValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''HomeAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeAddress2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeAddress2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblHomeAddress2Value control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeAddress2Value As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''HomeAddress3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeAddress3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeAddress3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeAddress3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblHomeAddress3values control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeAddress3values As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''HomeAddress4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeAddress4 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeAddress4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeAddress4 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblHomeAddress4Value control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeAddress4Value As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''City control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents City As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCity As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCityValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCityValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''State control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents State As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblState As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblStateValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStateValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Zip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Zip As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblZip As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblZipValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblZipValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''FaxNumberHome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FaxNumberHome As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblFaxNumberHome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFaxNumberHome As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFaxNumberHomeValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFaxNumberHomeValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''FaxNumberOffice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FaxNumberOffice As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblFaxNumberOffice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFaxNumberOffice As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFaxNumberOfficeValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFaxNumberOfficeValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''WorkAddressOne control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkAddressOne As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblWorkAddressOne control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkAddressOne As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblWorkAddressOneValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkAddressOneValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''WorkAddressTwo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkAddressTwo As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblWorkAddressTwo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkAddressTwo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblWorkAddressTwoValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkAddressTwoValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''WorkAddressThree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkAddressThree As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblWorkAddressThree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkAddressThree As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblWorkAddressThreeValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkAddressThreeValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''WorkCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkCity As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblWorkCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkCity As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblWorkCityValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkCityValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''WorkState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkState As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblWorkState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkState As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblWorkStateValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkStateValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''WorkZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkZip As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblWorkZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkZip As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblWorkZipValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkZipValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''EmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EmailAddress As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailAddress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmailAddressValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailAddressValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''FormerName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FormerName As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblFormerName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFormerName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFormerNameValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFormerNameValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''HomeTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeTelephone As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeTelephone As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblHomeTelephoneValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeTelephoneValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtHomeTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHomeTelephone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''maskedHomeTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents maskedHomeTelephone As Global.AjaxControlToolkit.MaskedEditExtender

        '''<summary>
        '''WorkTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkTelephone As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblWorkTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkTelephone As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblWorkTelephoneValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkTelephoneValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtWorkTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWorkTelephone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''maskedWorkTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents maskedWorkTelephone As Global.AjaxControlToolkit.MaskedEditExtender

        '''<summary>
        '''Degree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Degree As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblDegree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDegree As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lstbDegree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstbDegree As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''rqDegree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqDegree As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblDegreeValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDegreeValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''NameAppearOnCertificate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NameAppearOnCertificate As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblNameAppearOnCertificate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNameAppearOnCertificate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtNameAppearOnCertificate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNameAppearOnCertificate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqNameAppearOnCertificate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqNameAppearOnCertificate As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''DateOfBirth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DateOfBirth As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblDateOfBirth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDateOfBirth As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtBirthDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBirthDate As Global.AMC.DNN.Modules.CertRecert.Controls.Reusable.AMCDatetime

        '''<summary>
        '''rqDateOfBirth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqDateOfBirth As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtDateOfBirthValues control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDateOfBirthValues As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCurrentDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCurrentDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''CompareValidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CompareValidator1 As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''RequireSpecialTest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequireSpecialTest As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblRequireSpecialTest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRequireSpecialTest As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rblRequireSpecialTest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblRequireSpecialTest As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''hdRequireSpecialTestResponse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdRequireSpecialTestResponse As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdRequireSpecialTestQuestionId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdRequireSpecialTestQuestionId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdAnswerYes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdAnswerYes As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdAnswerNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdAnswerNo As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''requirespecialtestcomments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents requirespecialtestcomments As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblrequirespecialtestcomments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblrequirespecialtestcomments As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rqSpecialTestComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqSpecialTestComments As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''txtComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtComment As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RequireSpecialTestDesc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequireSpecialTestDesc As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblRequireSpecialTestDesc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRequireSpecialTestDesc As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlRequireSpecialTestDesc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlRequireSpecialTestDesc As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rqRequireSpecialTestDesc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqRequireSpecialTestDesc As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''hdKnownFromResponseID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdKnownFromResponseID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdKnownFromQuestionId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdKnownFromQuestionId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''MessagesLeft control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MessagesLeft As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblMessagesLeft control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessagesLeft As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtMessagesLeft control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMessagesLeft As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hdMessageLeftQuestionId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdMessageLeftQuestionId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdMessageLeftResponse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdMessageLeftResponse As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdMessageLeftAnswer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdMessageLeftAnswer As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''CertificationNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CertificationNumber As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblCertificationNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCertificationNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCertificationNumberValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCertificationNumberValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ReceiveMaterials control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReceiveMaterials As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblReceiveMaterials control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReceiveMaterials As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlReceiveMaterials control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlReceiveMaterials As Global.System.Web.UI.WebControls.DropDownList
    End Class
End Namespace
