'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls.Common

    Partial Public Class SupervisorUC

        '''<summary>
        '''hdIsIncomplete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdIsIncomplete As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdIsValidateFailed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdIsValidateFailed As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdSupervisorId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdSupervisorId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''lblSupervisorUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSupervisorUC As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''FormFillingInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FormFillingInstructions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblFormFillingInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFormFillingInstructions As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tblSupervisor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblSupervisor As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''NotifySupervisor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NotifySupervisor As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''chkNotifySupervisor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkNotifySupervisor As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblNotifySupervisor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNotifySupervisor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rqNotifySupervisor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqNotifySupervisor As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''ContactClass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ContactClass As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblContactClass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblContactClass As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rdlContactClass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdlContactClass As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''FirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FirstName As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFirstName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqFirstName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''MiddleName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MiddleName As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblMiddleName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMiddleName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtMiddleName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMiddleName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqMiddleName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqMiddleName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''LastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LastName As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLastName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqLastName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Title control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Title As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Institution control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Institution As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblInstitution control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInstitution As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtInstitution control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtInstitution As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqInstitution control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqInstitution As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''WorkAddress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkAddress1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblWorkAddress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkAddress1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtWorkAddress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWorkAddress1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqWorkAddress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqWorkAddress1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''WorkAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkAddress2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblWorkAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkAddress2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtWorkAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWorkAddress2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqWorkAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqWorkAddress2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''WorkAddress3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkAddress3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblWorkAddress3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkAddress3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtWorkAddress3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWorkAddress3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqWorkAddress3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqWorkAddress3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''WorkAddress4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WorkAddress4 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblWorkAddress4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWorkAddress4 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtWorkAddress4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWorkAddress4 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqWorkAddress4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqWorkAddress4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''City control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents City As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCity As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqCity As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''State control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents State As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblState As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlState As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rqState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqState As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Zip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Zip As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblZip As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtZip As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqZip As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''OfficeTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OfficeTelephone As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblOfficeTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOfficeTelephone As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtOfficeTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOfficeTelephone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqOfficeTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqOfficeTelephone As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''maskedOfficeTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents maskedOfficeTelephone As Global.AjaxControlToolkit.MaskedEditExtender

        '''<summary>
        '''maskedOfficeTelephoneValidator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents maskedOfficeTelephoneValidator As Global.AjaxControlToolkit.MaskedEditValidator

        '''<summary>
        '''EmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EmailAddress As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailAddress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailAddress As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqEmailAddress As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''regexEmailValid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents regexEmailValid As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''HomeAddress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeAddress1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeAddress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeAddress1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtHomeAddress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHomeAddress1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqHomeAddress1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqHomeAddress1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''HomeAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeAddress2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeAddress2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtHomeAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHomeAddress2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqHomeAddress2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqHomeAddress2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''HomeAddress3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeAddress3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeAddress3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeAddress3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtHomeAddress3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHomeAddress3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqHomeAddress3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqHomeAddress3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''HomeAddress4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeAddress4 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeAddress4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeAddress4 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtHomeAddress4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHomeAddress4 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqHomeAddress4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqHomeAddress4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''HomeCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeCity As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeCity As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtHomeCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHomeCity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqHomeCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqHomeCity As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''HomeState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeState As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeState As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlHomeState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlHomeState As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rqHomeState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqHomeState As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''HomeZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeZip As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeZip As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtHomeZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHomeZip As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqHomeZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqHomeZip As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''HomeTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeTelephone As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeTelephone As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtHomeTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHomeTelephone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqHomeTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqHomeTelephone As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''maskedHomeTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents maskedHomeTelephone As Global.AjaxControlToolkit.MaskedEditExtender

        '''<summary>
        '''maskedHomeTelephoneValidator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents maskedHomeTelephoneValidator As Global.AjaxControlToolkit.MaskedEditValidator

        '''<summary>
        '''HomeEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeEmailAddress As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblHomeEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHomeEmailAddress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtHomeEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHomeEmailAddress As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rqHomeEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqHomeEmailAddress As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''regexHomeEmailValid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents regexHomeEmailValid As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''PrefContactMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PrefContactMethod As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblPrefContactMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPrefContactMethod As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlPrefContactMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPrefContactMethod As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rqPrefContactMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rqPrefContactMethod As Global.System.Web.UI.WebControls.RequiredFieldValidator
    End Class
End Namespace
