'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace YourCompany.Modules.ModuleName1
    Partial Public Class Settings
        Protected WithEvents lblTemplate As System.Web.UI.UserControl
        Protected WithEvents txtTemplate As System.Web.UI.WebControls.TextBox
    End Class
End Namespace
