'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class EditModuleName1
    Protected WithEvents lblContent As DotNetNuke.UI.UserControls.LabelControl
    Protected WithEvents txtContent As DotNetNuke.UI.UserControls.TextEditor
    Protected WithEvents valContent As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents cmdUpdate As System.Web.UI.WebControls.LinkButton
    Protected WithEvents cmdCancel As System.Web.UI.WebControls.LinkButton
    Protected WithEvents cmdDelete As System.Web.UI.WebControls.LinkButton
    Protected WithEvents ctlAudit As DotNetNuke.UI.UserControls.ModuleAuditControl
End Class