'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls.Print

    Partial Public Class PrintRecert

        '''<summary>
        '''hdCurrentReCertOptionCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdCurrentReCertOptionCode As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''lblReCertUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReCertUC As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''printContainer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents printContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''sectionRegistrationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionRegistrationUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.RegistrationUC

        '''<summary>
        '''sectionRecertificationOptionUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionRecertificationOptionUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.RecertificationOptionUC

        '''<summary>
        '''sectionSupervisorUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionSupervisorUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.SupervisorUC

        '''<summary>
        '''sectionReferenceAndVerificationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionReferenceAndVerificationUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.ReferenceAndVerificationUC

        '''<summary>
        '''sectionLicensure control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionLicensure As Global.AMC.DNN.Modules.CertRecert.Controls.Common.Licensure

        '''<summary>
        '''sectionControlSubstanceAuthorizationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionControlSubstanceAuthorizationUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.ControlSubstanceAuthorizationUC

        '''<summary>
        '''sectionBoardCertificationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionBoardCertificationUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.BoardCertificationUC

        '''<summary>
        '''sectionStandardQuestionaireUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionStandardQuestionaireUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.StandardQuestionaireUC

        '''<summary>
        '''sectionRecertEligibilityUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionRecertEligibilityUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.RecertEligibilityUC

        '''<summary>
        '''sectionEducationCourseUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionEducationCourseUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.EducationCourseUC

        '''<summary>
        '''sectionCategoryCertifiedCME control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionCategoryCertifiedCME As Global.AMC.DNN.Modules.CertRecert.Controls.Common.CategoryCertifiedCME

        '''<summary>
        '''sectionCommunityServicePresentation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionCommunityServicePresentation As Global.AMC.DNN.Modules.CertRecert.Controls.Common.CommunityServicePresentation

        '''<summary>
        '''sectionCommunityServicePubication control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionCommunityServicePubication As Global.AMC.DNN.Modules.CertRecert.Controls.Common.CommunityServicePubication

        '''<summary>
        '''sectionCommunityServiceReview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionCommunityServiceReview As Global.AMC.DNN.Modules.CertRecert.Controls.Common.CommunityServiceReview

        '''<summary>
        '''sectionCommunityServiceVolunteerLeaderShip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionCommunityServiceVolunteerLeaderShip As Global.AMC.DNN.Modules.CertRecert.Controls.Common.CommunityServiceVolunteerLeaderShip

        '''<summary>
        '''sectionCommunityServiceVolunteerService control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionCommunityServiceVolunteerService As Global.AMC.DNN.Modules.CertRecert.Controls.Common.CommunityServiceVolunteerService

        '''<summary>
        '''sectionPracticeExperienceDetailsUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionPracticeExperienceDetailsUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.PracticeExperienceDetailsUC

        '''<summary>
        '''sectionProgramProjectActivities control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionProgramProjectActivities As Global.AMC.DNN.Modules.CertRecert.Controls.Common.ProgramProjectActivities

        '''<summary>
        '''sectionResearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionResearch As Global.AMC.DNN.Modules.CertRecert.Controls.Common.Research

        '''<summary>
        '''sectionOrganizationInvolvement control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionOrganizationInvolvement As Global.AMC.DNN.Modules.CertRecert.Controls.Common.OrganizationInvolvement

        '''<summary>
        '''sectionContinuingEducation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionContinuingEducation As Global.AMC.DNN.Modules.CertRecert.Controls.Common.ContinuingEducation

        '''<summary>
        '''sectionPublication control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionPublication As Global.AMC.DNN.Modules.CertRecert.Controls.Common.Publication

        '''<summary>
        '''sectionTeachingPresentation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionTeachingPresentation As Global.AMC.DNN.Modules.CertRecert.Controls.Common.TeachingPresentation

        '''<summary>
        '''sectionSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionSummary As Global.AMC.DNN.Modules.CertRecert.Controls.Common.Summary
    End Class
End Namespace
