'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls.Print

    Partial Public Class PrintCert

        '''<summary>
        '''printContainer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents printContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''sectionRegistrationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionRegistrationUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.RegistrationUC

        '''<summary>
        '''sectionSupervisorUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionSupervisorUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.SupervisorUC

        '''<summary>
        '''sectionExamChoiceUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionExamChoiceUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.ExamChoiceUC

        '''<summary>
        '''sectionRecertEligibilityUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionRecertEligibilityUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.RecertEligibilityUC

        '''<summary>
        '''sectionEducationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionEducationUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.EducationUC

        '''<summary>
        '''sectionLicensure control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionLicensure As Global.AMC.DNN.Modules.CertRecert.Controls.Common.Licensure

        '''<summary>
        '''sectionControlSubstanceAuthorizationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionControlSubstanceAuthorizationUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.ControlSubstanceAuthorizationUC

        '''<summary>
        '''sectionCategoryCertifiedCME control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionCategoryCertifiedCME As Global.AMC.DNN.Modules.CertRecert.Controls.Common.CategoryCertifiedCME

        '''<summary>
        '''sectionBoardCertificationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionBoardCertificationUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.BoardCertificationUC

        '''<summary>
        '''sectionPracticeExperienceDetailsUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionPracticeExperienceDetailsUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.PracticeExperienceDetailsUC

        '''<summary>
        '''sectionReferenceAndVerificationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionReferenceAndVerificationUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.ReferenceAndVerificationUC

        '''<summary>
        '''sectionStandardQuestionaireUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionStandardQuestionaireUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.StandardQuestionaireUC

        '''<summary>
        '''sectionProfessionalPracticeQuestionnaire control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionProfessionalPracticeQuestionnaire As Global.AMC.DNN.Modules.CertRecert.Controls.Common.ProfessionalPracticeQuestionnaire

        '''<summary>
        '''sectionProfessionalPracticeSetting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionProfessionalPracticeSetting As Global.AMC.DNN.Modules.CertRecert.Controls.Common.ProfessionalPracticeSetting

        '''<summary>
        '''sectionScopeUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionScopeUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.ScopeUC

        '''<summary>
        '''sectionDocumentationUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionDocumentationUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.DocumentationUC

        '''<summary>
        '''sectionProfessionalPracticeExperienceUC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sectionProfessionalPracticeExperienceUC As Global.AMC.DNN.Modules.CertRecert.Controls.Common.ProfessionalPracticeExperienceUC
    End Class
End Namespace
